name: MAUI App CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore dependencies
      run: dotnet restore mobile/SmartPole.Inventory.Mobile.sln

    - name: Build MAUI App
      run: dotnet build mobile/SmartPole.Inventory.App/SmartPole.Inventory.App.csproj --configuration Release --no-restore -f net9.0-android

    - name: Run Mobile Unit Tests
      run: dotnet test mobile/SmartPole.Inventory.UnitTests/SmartPole.Inventory.UnitTests.csproj --no-build --verbosity normal

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: maui-app-android
        path: mobile/SmartPole.Inventory.App/bin/Release/net9.0-android/*.apk
